# -*- coding: utf-8 -*-
"""Project.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hCt-zdBQSmGf_MmoO6D5d2FpyEQq_KXU
"""



# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import streamlit.components.v1 as components
# import pandas as pd
# from rdkit import Chem
# from rdkit.Chem import AllChem, Descriptors, rdMolDescriptors, rdMolTransforms
# import pubchempy as pcp
# import py3Dmol
# 
# # Page setup
# st.set_page_config(page_title="MolecuLens", page_icon="⚛️", layout="wide")
# 
# st.title("⚛️ MolecuLens: Interactive Molecular & Structural Explorer")
# 
# # Side bar Controls
# st.sidebar.header("🔬 Molecule Exploration")
# input_type = st.sidebar.radio("Search Method:", ["Compound Name", "Condensed Structure(SMILES String)"])
# 
# query = st.sidebar.text_input("Enter Search Term:", value="", placeholder="e.g. Any Compound")
# 
# # Expanded Visual Styles
# style_options = [
#     "Ball & Stick",
#     "Stick",
#     "Sphere / Spacefill",
#     "Wireframe / Line",
#     "Cross",
#     "VDW Surface",
#     "Solvent Accessible Surface (SAS)",
#     "Solvent Excluded Surface (SES)"
# ]
# view_style = st.sidebar.selectbox("3D Visualization Style:", style_options)
# show_element_labels = st.sidebar.checkbox("Show Element Symbols on Atoms", value=True)
# 
# # Function to render 3D view with CUSTOM COLORS and MULTIPLE STYLES
# def render_3d_mol(mol_3d, style_choice, display_labels):
#     mol_block = Chem.MolToMolBlock(mol_3d)
#     view = py3Dmol.view(width=650, height=500)
#     view.addModel(mol_block, 'mol')
# 
#     # 1. Base Geometry Styles
#     if style_choice == "Ball & Stick":
#         view.setStyle({'sphere': {'scale': 0.25}, 'stick': {'radius': 0.15}})
#     elif style_choice == "Stick":
#         view.setStyle({'stick': {'radius': 0.22}})
#     elif style_choice == "Sphere / Spacefill":
#         view.setStyle({'sphere': {'scale': 0.85}})
#     elif style_choice == "Wireframe / Line":
#         view.setStyle({'line': {'linewidth': 2.5}})
#     elif style_choice == "Cross":
#         view.setStyle({'cross': {'linewidth': 2.5, 'scale': 0.5}})
#     elif style_choice == "VDW Surface":
#         view.setStyle({'stick': {'radius': 0.15}})
#         view.addSurface(py3Dmol.VDW, {'opacity': 0.6, 'color': 'lightblue'})
#     elif style_choice == "Solvent Accessible Surface (SAS)":
#         view.setStyle({'stick': {'radius': 0.15}})
#         view.addSurface(py3Dmol.SAS, {'opacity': 0.6, 'color': 'lightgreen'})
#     elif style_choice == "Solvent Excluded Surface (SES)":
#         view.setStyle({'stick': {'radius': 0.15}})
#         view.addSurface(py3Dmol.SES, {'opacity': 0.6, 'color': 'orange'})
# 
#     # 2. CUSTOM ELEMENT COLORS (O -> Blue, H -> Red, N -> Purple, C -> Gray)
#     if style_choice not in ["Wireframe / Line", "Cross"]:
#         view.addStyle({'elem': 'O'}, {'stick': {'color': 'blue', 'radius': 0.22}, 'sphere': {'color': 'blue', 'scale': 0.32}})
#         view.addStyle({'elem': 'H'}, {'stick': {'color': 'red', 'radius': 0.12}, 'sphere': {'color': 'red', 'scale': 0.20}})
#         view.addStyle({'elem': 'N'}, {'stick': {'color': 'purple', 'radius': 0.22}, 'sphere': {'color': 'purple', 'scale': 0.32}})
#         view.addStyle({'elem': 'C'}, {'stick': {'color': 'darkgray', 'radius': 0.18}, 'sphere': {'color': 'darkgray', 'scale': 0.28}})
# 
#     # 3. Dynamic Property Labels
#     if display_labels:
#         view.addPropertyLabels('elem', {}, {
#             'fontSize': 11,
#             'fontColor': 'black',
#             'showBackground': True,
#             'backgroundColor': 'white',
#             'backgroundOpacity': 0.7
#         })
# 
#     view.setBackgroundColor('white')
#     view.zoomTo()
#     return view._make_html()
# 
# # Helper: Compute 3D Bond Angles
# def calculate_bond_angles(mol_3d):
#     conf = mol_3d.GetConformer()
#     angles_data = []
# 
#     for atom_b in mol_3d.GetAtoms():
#         b_idx = atom_b.GetIdx()
#         neighbors = atom_b.GetNeighbors()
# 
#         if len(neighbors) >= 2:
#             for i in range(len(neighbors)):
#                 for j in range(i + 1, len(neighbors)):
#                     a_idx = neighbors[i].GetIdx()
#                     c_idx = neighbors[j].GetIdx()
# 
#                     angle = rdMolTransforms.GetBondAngle(conf, a_idx, b_idx, c_idx)
# 
#                     a_sym = neighbors[i].GetSymbol()
#                     b_sym = atom_b.GetSymbol()
#                     c_sym = neighbors[j].GetSymbol()
# 
#                     triplet_label = f"{a_sym}(#{a_idx}) - {b_sym}(#{b_idx}) - {c_sym}(#{c_idx})"
#                     angles_data.append({"Central Atom": f"{b_sym} (#{b_idx})", "Triplet": triplet_label, "Angle (°)": round(angle, 2)})
# 
#     return pd.DataFrame(angles_data)
# 
# # Helper: Element Counts
# def get_element_counts(mol_3d):
#     counts = {}
#     for atom in mol_3d.GetAtoms():
#         sym = atom.GetSymbol()
#         counts[sym] = counts.get(sym, 0) + 1
#     return counts
# 
# # Main Logic: Check if user has entered a search term
# if query.strip():
#     try:
#         smiles = ""
#         compound_name = query.strip()
# 
#         if input_type.startswith("Compound"):
#             compounds = pcp.get_compounds(compound_name, 'name')
#             if compounds:
#                 smiles = compounds[0].isomeric_smiles
#                 compound_name = compounds[0].iupac_name or compound_name
#             else:
#                 st.error(f"Compound '{compound_name}' not found on PubChem. Please check the spelling or try a SMILES string.")
#                 st.stop()
#         else:
#             smiles = compound_name
# 
#         mol = Chem.MolFromSmiles(smiles)
#         if mol is None:
#             st.error("Invalid SMILES input string. Please enter a valid molecular structure string.")
#             st.stop()
# 
#         # Add Hydrogen atoms & Generate 3D Conformation
#         mol_3d = Chem.AddHs(mol)
#         AllChem.EmbedMolecule(mol_3d, randomSeed=42)
#         AllChem.MMFFOptimizeMolecule(mol_3d)
# 
#         col_left, col_right = st.columns([3, 2])
# 
#         with col_left:
#             st.subheader(f"3D Structure: {query.strip().capitalize()}")
#             st.markdown("""
#             **Element Color Key:**
#             🔵 **Oxygen (Blue)** | 🔴 **Hydrogen (Red)** | 🟣 **Nitrogen (Purple)** | ⚪ **Carbon (Gray)**
#             """)
#             html_code = render_3d_mol(mol_3d, view_style, show_element_labels)
#             components.html(html_code, height=520)
# 
#         with col_right:
#             # Multi-Tab Dashboard
#             tab1, tab2, tab3 = st.tabs(["📊 General Properties", "⚛️ Element Composition", "📐 3D Bond Angles"])
# 
#             with tab1:
#                 st.markdown("### Core Identifiers & Mass")
#                 c1, c2, c3 = st.columns(3)
#                 c1.metric("Formula", rdMolDescriptors.CalcMolFormula(mol))
#                 c2.metric("Mol. Weight", f"{Descriptors.MolWt(mol):.2f} g/mol")
#                 c3.metric("Exact Mass", f"{Descriptors.ExactMolWt(mol):.2f}")
# 
#                 st.markdown("### Physicochemical & Lipophilicity")
#                 p1, p2, p3 = st.columns(3)
#                 p1.metric("LogP", f"{Descriptors.MolLogP(mol):.2f}")
#                 p2.metric("TPSA", f"{Descriptors.TPSA(mol):.2f} Å²")
#                 p3.metric("Molar Refractivity", f"{Descriptors.MolMR(mol):.2f}")
# 
#                 st.markdown("### Structural & Complexity Descriptors")
#                 s1, s2, s3 = st.columns(3)
#                 s1.metric("Fsp3 (sp³ Carbon Frac)", f"{Descriptors.FractionCSP3(mol):.2f}")
#                 s2.metric("Stereocenters", f"{len(Chem.FindMolChiralCenters(mol, includeUnassigned=True))}")
#                 s3.metric("Net Charge", f"{Chem.GetFormalCharge(mol)}")
# 
#                 st.divider()
#                 st.markdown(f"**Ring Profile:** Total: `{Descriptors.NumRings(mol)}` | Aromatic: `{Descriptors.NumAromaticRings(mol)}` | Saturated: `{Descriptors.NumSaturatedRings(mol)}`")
#                 st.markdown(f"**Bond & Atom Profile:** Heavy Atoms: `{mol.GetNumHeavyAtoms()}` | Total Atoms: `{mol_3d.GetNumAtoms()}` | Rotatable Bonds: `{Descriptors.NumRotatableBonds(mol)}`")
#                 st.markdown(f"**H-Bonding & Electrons:** Donors: `{Descriptors.NumHDonors(mol)}` | Acceptors: `{Descriptors.NumHAcceptors(mol)}` | Valence e⁻: `{Descriptors.NumValenceElectrons(mol)}`")
# 
#             with tab2:
#                 st.markdown("### Atom Breakdown by Element")
#                 elem_counts = get_element_counts(mol_3d)
# 
#                 cols = st.columns(len(elem_counts))
#                 for idx, (elem, count) in enumerate(elem_counts.items()):
#                     cols[idx % len(cols)].metric(f"Element: {elem}", f"{count} atoms")
# 
#                 st.divider()
#                 st.markdown("**Canonical SMILES:**")
#                 st.code(smiles, language="text")
# 
#             with tab3:
#                 st.markdown("### 3D Spatial Bond Angle Calculations")
#                 df_angles = calculate_bond_angles(mol_3d)
# 
#                 if not df_angles.empty:
#                     avg_angle = df_angles["Angle (°)"].mean()
#                     min_angle = df_angles["Angle (°)"].min()
#                     max_angle = df_angles["Angle (°)"].max()
# 
#                     a1, a2, a3 = st.columns(3)
#                     a1.metric("Avg Angle", f"{avg_angle:.1f}°")
#                     a2.metric("Min Angle", f"{min_angle:.1f}°")
#                     a3.metric("Max Angle", f"{max_angle:.1f}°")
# 
#                     st.markdown("**Calculated Triplet Bond Angles:**")
#                     st.dataframe(df_angles, height=220, use_container_width=True)
#                 else:
#                     st.info("Molecule does not have enough bonded triplets to form bond angles.")
# 
#     except Exception as e:
#         st.error(f"Error generating molecular data: {str(e)}")
# else:
#     # Initial Landing Page Content when no molecule is searched
#     st.info("👈 Enter a compound name or SMILES string in the sidebar to begin exploring!")
# 
#     st.markdown("""
#     ### Welcome to **MolecuLens** 👋
# 
#     **MolecuLens** is an interactive chemoinformatics platform designed for exploring 3D molecular structures, atom geometry, and physicochemical properties in real time.
# 
#     ---
# 
#     #### 🌟 Platform Capabilities
# 
#     * **3D Spatial Conformation Engine:** Converts chemical names & 2D SMILES into energy-minimized 3D conformations using **RDKit's MMFF (Merck Molecular Force Field)** algorithm.
#     * **Interactive WebGL Visualizer:** Click, drag, rotate, and zoom 3D structures powered by **py3Dmol**.
#     * **Custom Element Color Key:**
#       * 🔵 **Oxygen ($\text{O}$): Blue**
#       * 🔴 **Hydrogen ($\text{H}$): Red**
#       * 🟣 **Nitrogen ($\text{N}$): Purple**
#       * ⚪ **Carbon ($\text{C}$): Dark Gray**
#     * **8 Structural Representations:** Ball & Stick, Stick, Spacefill, Wireframe, Cross, VDW Surface, Solvent Accessible Surface (SAS), and Solvent Excluded Surface (SES).
#     * **Chemoinformatics Suite:** Instant calculation of Molecular Weight, LogP, TPSA, $F_{sp3}$ complexity, chiral stereocenters, ring systems, and exact 3D bond angles ($\text{X}-\text{Y}-\text{Z}$ triplets).
# 
#     ---
# 
#     #### 🚀 How to Get Started
#     1. Look at the **sidebar on the left**.
#     2. Choose **Compound Name** (e.g., *Aspirin*, *Penicillin*, *Curcumin*, *Ibuprofen*) or **SMILES String**.
#     3. Type your search term and press **Enter**.
#     """)

!curl ipv4.icanhazip.com

!wget -q -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared

!streamlit run app.py & ./cloudflared tunnel --url http://localhost:8501
