# -*- coding: utf-8 -*-
"""Requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DytO6D5MTot3aqb0AdrM71u2JQutw9uq
"""

streamlit
rdkit
py3Dmol
pubchempy